<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VehicleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('vehicles')->insert([
            [
                'brand' => 'Suzuki Ertiga',
                'year' => 2019,
                'plate_number' => 'B 1122 ERG',
                'transmission' => 'manual',
                'fuel_type' => 'gasoline',
                'capacity' => 7,
                'price_per_day' => 300000,
                'description' => 'Mobil keluarga dengan handling ringan dan nyaman.',
                'photo' => 'vehicles/ertiga.jpg',
                'vehicle_type' => 'car',
                'status' => 'Available',
            ],
            [
                'brand' => 'Toyota Fortuner',
                'year' => 2023,
                'plate_number' => 'B 3344 FRT',
                'transmission' => 'automatic',
                'fuel_type' => 'diesel',
                'capacity' => 7,
                'price_per_day' => 850000,
                'description' => 'SUV tangguh untuk perjalanan jauh dengan tenaga besar.',
                'photo' => 'vehicles/fortuner.jpg',
                'vehicle_type' => 'car',
                'status' => 'Available',
            ],
            [
                'brand' => 'Daihatsu Sigra',
                'year' => 2021,
                'plate_number' => 'B 5566 SGR',
                'transmission' => 'manual',
                'fuel_type' => 'gasoline',
                'capacity' => 7,
                'price_per_day' => 250000,
                'description' => 'Mobil irit dan cocok untuk perjalanan dalam kota.',
                'photo' => 'vehicles/sigra.jpg',
                'vehicle_type' => 'car',
                'status' => 'Available',
            ],
            [
                'brand' => 'Yamaha NMAX',
                'year' => 2022,
                'plate_number' => 'BE 7788 NMX',
                'transmission' => 'automatic',
                'fuel_type' => 'gasoline',
                'capacity' => 2,
                'price_per_day' => 150000,
                'description' => 'Motor matic premium nyaman untuk perjalanan jauh.',
                'photo' => 'vehicles/nmax.jpg',
                'vehicle_type' => 'motorcycle',
                'status' => 'Available',
            ],
            [
                'brand' => 'Kawasaki Ninja 250',
                'year' => 2021,
                'plate_number' => 'BE 9900 NJA',
                'transmission' => 'manual',
                'fuel_type' => 'gasoline',
                'capacity' => 2,
                'price_per_day' => 300000,
                'description' => 'Motor sport bertenaga untuk pecinta kecepatan.',
                'photo' => 'vehicles/ninja.jpg',
                'vehicle_type' => 'motorcycle',
                'status' => 'Available',
            ],
            [
                'brand' => 'Isuzu Elf',
                'year' => 2018,
                'plate_number' => 'B 4455 ELF',
                'transmission' => 'manual',
                'fuel_type' => 'diesel',
                'capacity' => 12,
                'price_per_day' => 650000,
                'description' => 'Kendaraan besar cocok untuk rombongan atau wisata.',
                'photo' => 'vehicles/elf.jpg',
                'vehicle_type' => 'car',
                'status' => 'Available',
            ],
            [
                'brand' => 'Honda Vario 125',
                'year' => 2020,
                'plate_number' => 'BE 2233 VAR',
                'transmission' => 'automatic',
                'fuel_type' => 'gasoline',
                'capacity' => 2,
                'price_per_day' => 120000,
                'description' => 'Motor matic ringan dan irit untuk aktivitas harian.',
                'photo' => 'vehicles/vario.jpg',
                'vehicle_type' => 'motorcycle',
                'status' => 'Available',
            ],
            [
                'brand' => 'Toyota Hilux',
                'year' => 2022,
                'plate_number' => 'B 7788 HLX',
                'transmission' => 'manual',
                'fuel_type' => 'diesel',
                'capacity' => 5,
                'price_per_day' => 600000,
                'description' => 'Mobil double cabin untuk pekerjaan berat dan offroad.',
                'photo' => 'vehicles/hilux.jpg',
                'vehicle_type' => 'car',
                'status' => 'Available',
            ],
            [
                'brand' => 'Toyota Avanza',
                'year' => 2021,
                'plate_number' => 'B 1234 XYZ',
                'transmission' => 'automatic',
                'fuel_type' => 'gasoline',
                'capacity' => 7,
                'price_per_day' => 350000,
                'description' => 'Mobil keluarga irit BBM dan nyaman digunakan.',
                'photo' => 'vehicles/avanza.jpg',
                'vehicle_type' => 'car',
                'status' => 'Available',
            ],
            [
                'brand' => 'Honda Beat',
                'year' => 2020,
                'plate_number' => 'BE 5678 ABC',
                'transmission' => 'manual',
                'fuel_type' => 'gasoline',
                'capacity' => 2,
                'price_per_day' => 100000,
                'description' => 'Motor matic irit BBM dan lincah di jalan.',
                'photo' => 'vehicles/beat.jpg',
                'vehicle_type' => 'motorcycle',
                'status' => 'Available',
            ],
            [
                'brand' => 'Mitsubishi Xpander',
                'year' => 2022,
                'plate_number' => 'B 9876 DEF',
                'transmission' => 'automatic',
                'fuel_type' => 'gasoline',
                'capacity' => 7,
                'price_per_day' => 450000,
                'description' => 'Mobil MPV premium dengan kenyamanan ekstra.',
                'photo' => 'vehicles/xpander.jpg',
                'vehicle_type' => 'car',
                'status' => 'Available',
            ],
        ]);
    }
}
